### ISSUE TITLE
Module not found error with sveltekit and typescript

### ISSUE THREAD

**Issue by Jakeii** [chainlist/svelte-forms#47]
Getting the following error with vite@2.7.10 and @sveltejs/kit@1.0.0-next.215

```
Cannot find module '/Users/.../node_modules/svelte-forms/form' imported from /Users/.../node_modules/svelte-forms/index.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/.../node_modules/svelte-forms/form' imported from /Users/.../plate-svelte-kit/node_modules/svelte-forms/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:416:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

can be reproduced by creating a new sveltekit project using `npm init svelte@next my-app`, installing, opting to use typescript and trying to use `svelte-forms`

**Comment by chainlist** [comment]
Hi @Jakeii, 

Indeed there is an error. I am on it.
I wonder why it stops working with SSR all of a sudden tho'

**Comment by Jakeii** [comment]
> Hi @Jakeii,
> 
> Indeed there is an error. I am on it. I wonder why it stops working with SSR all of a sudden tho'

Changing all imports to include the file extensions seemed to fix it, not sure why, or if it breaks anything else though.

**Comment by chainlist** [comment]
Why do you mean by "to include the file extensions"?

That might be a error caused by a change in how vite resolve its dependencies.

**Comment by Jakeii** [comment]
> Why do you mean by "to include the file extensions"?
> 
> That might be a error caused by a change in how vite resolve its dependencies.

Inside the svelte-forms module I changed all imports to include '.js' and it fixed the issue.

**Comment by chainlist** [comment]
That's interesting!

Thanks for your feedback

**Comment by Jakeii** [comment]
hey again @chainlist, have dug into this a bit. So I think svelte-forms should be including the '.js' according to the ES6 import spec. I think the reason it was working before was because vite was using commonjs to load ssr modules until 2.7.0 when https://github.com/vitejs/vite/pull/5197 added native support for 'import' for ssr which broke svelte-forms.

**Comment by chainlist** [comment]
Thanks for you digging!

It's quite annoying tho' to have to put the `.js` extension for everything we want to import now.
Not really the way we want to use NPM modules nowadays.

I'm still digging into vite config to check if there is a way to omit this issue

**Comment by chainlist** [comment]
Issue has been fixed in the latest version `2.0.11`.

Thanks for your precious help, it saved me a lot of investigation time! Much appreciated!

**Comment by hsb-tonmoy** [comment]
I'm still having this issue, with the latest version. Any idea why? #55

**Comment by xcorat** [comment]
Same... It comes up only when I refresh the page. The first load with the form works, but if I refresh the browser, it throws an error.. any suggestions?
